#! /bin/bash

if [  -n "$(pgrep  -f  Scheduler)" ]
then
echo "$(pgrep -a -f  Scheduler)"
echo Scheduler is running, kill it first. Exiting...
exit
fi

if  [ "$1" = "nolog" ] ; then

 java -cp /home/pi/git/Scheduler:/home/pi/git/Scheduler/lib/'*':/home/pi/git/RGPIO/lib/'*' scheduler/Scheduler server control=true verbosity=1

else

 loglink=/home/pi/Scheduler/logs/Schedulerlogfile
 logfile=/home/pi/Scheduler/logs/log-`date +%d-%m@%H:%M`
 [ -f $loglink ] && rm $loglink
 touch $logfile
 ln -s $logfile $loglink

 (
# cd /home/pi/git/Scheduler/run
 java -cp /home/pi/git/Scheduler:/home/pi/git/Scheduler/lib/'*':/home/pi/git/RGPIO/lib/'*' scheduler/Scheduler server control=true verbosity=1
 )  >> $loglink 2>&1 &

fi
